package arayuz;

import baglanti.*;
import db.Ogrenci;
import db.Ogretmen;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class menu extends javax.swing.JFrame {

    private baglanti bglnt = new baglanti();

    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        yoneticiidtxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        yoneticisifretxt = new javax.swing.JPasswordField();
        yoneticigirisbtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        ogretmenidtxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ogretmensifretxt = new javax.swing.JPasswordField();
        ogretmengirisbtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        ogrenciidtxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ogrencisifretxt = new javax.swing.JPasswordField();
        ogrencigirisbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 22)); // NOI18N
        jLabel1.setText("PROJE DERSÝ KAYIT SÝSTEMÝ ");

        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel9.setText("Yönetici ID : ");

        yoneticiidtxt.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        yoneticiidtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yoneticiidtxtActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel10.setText("Þifre :");

        yoneticisifretxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yoneticisifretxtActionPerformed(evt);
            }
        });

        yoneticigirisbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        yoneticigirisbtn.setText("GÝRÝÞ");
        yoneticigirisbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yoneticigirisbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(yoneticiidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(yoneticisifretxt, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(yoneticigirisbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel9))
                    .addComponent(yoneticiidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(yoneticisifretxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addComponent(yoneticigirisbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Yönetici Giriþ", jPanel1);

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel5.setText("Öðretmen ID : ");

        ogretmenidtxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ogretmenidtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ogretmenidtxtActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel6.setText("Þifre :");

        ogretmensifretxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ogretmensifretxtActionPerformed(evt);
            }
        });

        ogretmengirisbtn.setText("GÝRÝÞ");
        ogretmengirisbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ogretmengirisbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(ogretmenidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(ogretmensifretxt, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ogretmengirisbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel5))
                    .addComponent(ogretmenidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(ogretmensifretxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addComponent(ogretmengirisbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Öðretmen Giriþ", jPanel2);

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel7.setText("Öðrenci ID : ");

        ogrenciidtxt.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        ogrenciidtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ogrenciidtxtActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel8.setText("Þifre :");

        ogrencisifretxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ogrencisifretxtActionPerformed(evt);
            }
        });

        ogrencigirisbtn.setText("GÝRÝÞ");
        ogrencigirisbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ogrencigirisbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(ogrenciidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(ogrencisifretxt, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ogrencigirisbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel7))
                    .addComponent(ogrenciidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(ogrencisifretxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addComponent(ogrencigirisbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Öðrenci Giriþ", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(jLabel1)
                .addContainerGap(237, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ogretmenidtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ogretmenidtxtActionPerformed

    }//GEN-LAST:event_ogretmenidtxtActionPerformed

    private void ogretmensifretxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ogretmensifretxtActionPerformed

    }//GEN-LAST:event_ogretmensifretxtActionPerformed

    private void ogretmengirisbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ogretmengirisbtnActionPerformed

        Connection c = bglnt.dbcon();
        Statement st = null;
        ResultSet rs = null;
        ResultSet rs1 = null;
        boolean flag = false;
        if (ogretmenidtxt.getText().length() == 0 || ogretmensifretxt.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "L?tfen Bo? Alanlar? Doldurunuz!");
            ogretmenidtxt.setText("");
            ogretmensifretxt.setText("");
        } else {

            try {
                st = c.createStatement();
                rs = st.executeQuery("select * from \"Hocalar\"");
                rs1 = bilgial("select * from \"Sistem\" ");
                while (rs.next()) {
                    if ((ogretmenidtxt.getText().equalsIgnoreCase(rs.getString("sicilNo"))) && (ogretmensifretxt.getText().equalsIgnoreCase(rs.getString("hSifre")))) {
                        flag = true;
                        Ogretmen ogretmen = new Ogretmen();
                        ogretmen.setSicilNo(rs.getInt("sicilNo"));
                        ogretmen.sethSifre(rs.getString("hSifre"));

                        ogretmenidtxt.setText("");
                        ogretmensifretxt.setText("");

                        hocaFrame hocaFrame = new hocaFrame();
                        hocaFrame.bilgiyaz(ogretmen);

                        while (rs1.next()) {

                            if (rs1.getBoolean("asama") == false) {
                                hocaFrame.tablobilgigor(hocaFrame.hocataleptable);
                                hocaFrame.kritersilbtn.setEnabled(true);
                                hocaFrame.kriterbtn.setEnabled(true);
                                hocaFrame.ilgibtn.setEnabled(true);
                            } else {

                                hocaFrame.kritersilbtn.setEnabled(false);
                                hocaFrame.kriterbtn.setEnabled(false);
                                hocaFrame.ilgibtn.setEnabled(false);
                            }

                        }

                        hocaFrame.dersler(ogretmen);

                        dispose();
                        hocaFrame.setVisible(true);

                    } else {

                    }
                }

                if (flag == false) {
                    JOptionPane.showMessageDialog(null, "Kullanici bilgileri yanlis");
                    ogretmenidtxt.setText("");
                    ogretmensifretxt.setText("");
                }

            } catch (SQLException ex) {
                Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    if (rs != null) {
                        rs.close();
                    }
                    if (rs1 != null) {
                        rs1.close();
                    }
                    if (st != null) {
                        st.close();
                    }
                    if (c != null) {
                        c.close();
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_ogretmengirisbtnActionPerformed

    private void ogrenciidtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ogrenciidtxtActionPerformed

    }//GEN-LAST:event_ogrenciidtxtActionPerformed

    private void ogrencisifretxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ogrencisifretxtActionPerformed
    }//GEN-LAST:event_ogrencisifretxtActionPerformed

    public ResultSet bilgial(String query) {
        Connection c = bglnt.dbcon();
        Statement st = null;
        ResultSet rs = null;

        try {
            st = c.createStatement();
            rs = st.executeQuery(query);
            return rs;
        } catch (SQLException ex) {
            Logger.getLogger(yoneticiFrame.class.getName()).log(Level.SEVERE, null, ex);
            return null;
        } finally {
            try {
                // rs.close(); 
                st.close();
                c.close();
            } catch (SQLException ex) {
                Logger.getLogger(hocaFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }

    private void ogrencigirisbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ogrencigirisbtnActionPerformed

        Connection c = bglnt.dbcon();
        Statement st = null;
        ResultSet rs = null;
        ResultSet rs1 = null;
        boolean flag = false;
        if (ogrenciidtxt.getText().length() == 0 || ogrencisifretxt.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "L?tfen Bo? Alanlar? Doldurunuz!");
            ogrenciidtxt.setText("");
            ogrencisifretxt.setText("");
        } else {

            try {
                st = c.createStatement();
                rs = st.executeQuery("select * from \"Ogrenciler\"");
                rs1 = bilgial("select * from \"Sistem\" ");
                while (rs.next()) {
                    if ((ogrenciidtxt.getText().equalsIgnoreCase(rs.getString("ogrNo"))) && (ogrencisifretxt.getText().equalsIgnoreCase(rs.getString("ogrSifre")))) {
                        flag = true;

                        Ogrenci ogrenci = new Ogrenci();
                        ogrenci.setOgrNo(rs.getInt("ogrNo"));
                        ogrenci.setOgrSifre(rs.getString("ogrSifre"));
                        ogrenci.setGNO(rs.getDouble("GNO"));
                        ogrenci.setOgrAd(rs.getString("ogrAd"));
                        ogrenci.setOgrSoyad(rs.getString("ogrSoyad"));
                        ogrenci.setToplamTalep(rs.getInt("toplamTalep"));
                        ogrenci.setTalepOnay(rs.getInt("talepOnay"));

                        ogrenciidtxt.setText("");
                        ogrencisifretxt.setText("");

                        ogrFrame ogrFrame = new ogrFrame();
                        ogrFrame.bilgiyaz(ogrenci);

                        while (rs1.next()) {

                            if (rs1.getBoolean("asama") == false) {

                                ogrFrame.tablotalep(ogrFrame.derssecimtable);
                                ogrFrame.tablo(ogrFrame.ogrtaleplertable);
                                ogrFrame.tablotalep(ogrFrame.ilgihocatable);
                                ogrFrame.belgebtn.setEnabled(true);
                                if (ogrFrame.ogrenci.getDersad() != null) {
                                    ogrFrame.filtrebtn.setEnabled(true);
                                } else {
                                    ogrFrame.filtrebtn.setEnabled(false);
                                }

                            } else {
                                ogrFrame.belgebtn.setEnabled(false);

                                ogrFrame.derssecbtn.setEnabled(false);
                                ogrFrame.filtrebtn.setEnabled(false);

                            }

                        }

                        dispose();
                        ogrFrame.setVisible(true);

                    } else {

                    }
                }
                if (flag == false) {
                    JOptionPane.showMessageDialog(null, "Kullanici bilgileri yanlis");
                    ogrenciidtxt.setText("");
                    ogrencisifretxt.setText("");
                }

            } catch (SQLException ex) {
                Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    if (rs != null) {
                        rs.close();
                    }
                    if (st != null) {
                        st.close();
                    }
                    if (c != null) {
                        c.close();
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

    }//GEN-LAST:event_ogrencigirisbtnActionPerformed

    private void yoneticiidtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yoneticiidtxtActionPerformed

    }//GEN-LAST:event_yoneticiidtxtActionPerformed

    private void yoneticisifretxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yoneticisifretxtActionPerformed

    }//GEN-LAST:event_yoneticisifretxtActionPerformed

    private void yoneticigirisbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yoneticigirisbtnActionPerformed

        Connection c = bglnt.dbcon();
        Statement st = null;
        ResultSet rs = null;
        boolean flag = false;
        if (yoneticiidtxt.getText().length() == 0 || yoneticisifretxt.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Lütfen Boþ Alanlarý Doldurunuz!");
            yoneticiidtxt.setText("");
            yoneticisifretxt.setText("");
        } else {

            try {
                st = c.createStatement();
                rs = st.executeQuery("select * from \"Yonetici\"");

                while (rs.next()) {
                    if ((yoneticiidtxt.getText().equalsIgnoreCase(rs.getString("yonID"))) && (yoneticisifretxt.getText().equalsIgnoreCase(rs.getString("yonSifre")))) {
                        flag = true;

                        yoneticiidtxt.setText("");
                        yoneticisifretxt.setText("");

                        yoneticiFrame yonFrame = new yoneticiFrame();

                        dispose();
                        yonFrame.setVisible(true);
                        //yonFrame.sistem(yonFrame.ogrhocatable);

                    } else {

                    }
                }
                if (flag == false) {
                    JOptionPane.showMessageDialog(null, "Kullanici bilgileri yanlis");
                    yoneticiidtxt.setText("");
                    yoneticisifretxt.setText("");
                }

            } catch (SQLException ex) {
                Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    if (rs != null) {
                        rs.close();
                    }
                    if (st != null) {
                        st.close();
                    }
                    if (c != null) {
                        c.close();
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }


    }//GEN-LAST:event_yoneticigirisbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton ogrencigirisbtn;
    private javax.swing.JTextField ogrenciidtxt;
    private javax.swing.JPasswordField ogrencisifretxt;
    private javax.swing.JButton ogretmengirisbtn;
    private javax.swing.JTextField ogretmenidtxt;
    private javax.swing.JPasswordField ogretmensifretxt;
    private javax.swing.JButton yoneticigirisbtn;
    private javax.swing.JTextField yoneticiidtxt;
    private javax.swing.JPasswordField yoneticisifretxt;
    // End of variables declaration//GEN-END:variables
}
